apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/secret.yaml
- manifests/configmap.yaml
- manifests/db/statefulset.yaml
- manifests/db/service.yaml
- manifests/log-output/deployment.yaml
- manifests/log-output/service.yaml
- manifests/pingpong/deployment.yaml
- manifests/pingpong/service.yaml
- manifests/ingress.yaml