apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- Project/manifests/configmap.yaml
- Project/manifests/db/statefulset.yaml
- Project/manifests/db/service.yaml
- Project/manifests/frontend/deployment.yaml
- Project/manifests/frontend/service.yaml
- Project/manifests/backend/deployment.yaml
- Project/manifests/backend/service.yaml
- Project/manifests/cron/job.yaml
- Project/manifests/ingress.yaml
images:
- name: PROJECT/BACKEND
  newName: dwk-backend
- name: PROJECT/FRONTEND
  newName: dwk-frontend
- name: PROJECT/CRON
  newName: dwk-cron
