apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log-pingpong
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: tsadom/dwkex:v3.2.pingpong.13
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 5000
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_HOST
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_DATABASE
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_PORT
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_USER