apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong
  namespace: log-pingpong
spec:
  template:
    metadata:
      name: pingpong-dwk
    spec:
      containers:
        - image: tsadom/dwkex:pingpong.6
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_HOST
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_DATABASE
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_PORT
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: PG_USER