apiVersion: v1
kind: Service
metadata:
  namespace: log-pingpong
  name: pingpong-svc
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
