# permissions for end users to edit dummysites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummysite-editor-role
rules:
- apiGroups:
  - dummysite.stable.dwk
  resources:
  - dummysites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dummysite.stable.dwk
  resources:
  - dummysites/status
  verbs:
  - get
