apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log-pingpong
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: tsadom/dwkex:14.l4