apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/secret.yaml
- manifests/configmap.yaml
- manifests/db/statefulset.yaml
- manifests/db/service.yaml
- manifests/frontend/deployment.yaml
- manifests/frontend/service.yaml
- manifests/backend/deployment.yaml
- manifests/backend/service.yaml
- manifests/cron/job.yaml
- manifests/ingress.yaml
images:
- name: PROJECT/BACKEND
  newName: tsadom/dwkex:v3.3.backend.6
- name: PROJECT/FRONTEND
  newName: tsadom/dwkex:v3.3.frontend.6
- name: PROJECT/CRON
  newName: tsadom/dwkex:v3.3.cron.6