apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/db/statefulset.yaml
- manifests/db/service.yaml
- manifests/frontend/deployment.yaml
- manifests/frontend/service.yaml
- manifests/backend/rollout.yaml
- manifests/backend/service.yaml
- manifests/backend/horizontalpodautoscaler.yaml
- manifests/cron/job.yaml
- manifests/broadcaster/deployment.yaml
- manifests/ingress.yaml
- manifests/analysistemplate.yaml
- persistent/persistentvolumeclaim.yaml
- persistent/persistentvolume.yaml
images:
- name: PROJECT/BACKEND
  newName: tsa-dom/dwkex
  newTag: backend.6766a5049746623efc4ee30c5fa37d5321c2d19d
- name: PROJECT/BROADCASTER
  newName: tsa-dom/dwkex
  newTag: broadcaster.6766a5049746623efc4ee30c5fa37d5321c2d19d
- name: PROJECT/CRON
  newName: tsa-dom/dwkex
  newTag: cron.6766a5049746623efc4ee30c5fa37d5321c2d19d
- name: PROJECT/FRONTEND
  newName: tsa-dom/dwkex
  newTag: frontend.6766a5049746623efc4ee30c5fa37d5321c2d19d
