apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/db/statefulset.yaml
- manifests/db/service.yaml
- manifests/frontend/deployment.yaml
- manifests/frontend/service.yaml
- manifests/backend/rollout.yaml
- manifests/backend/service.yaml
- manifests/backend/horizontalpodautoscaler.yaml
- manifests/cron/job.yaml
- manifests/broadcaster/deployment.yaml
- manifests/ingress.yaml
- manifests/analysistemplate.yaml
- persistent/persistentvolumeclaim.yaml
- persistent/persistentvolume.yaml
images:
- name: PROJECT/BACKEND
  newName: tsadom/dwkex
  newTag: backend.35665ff4660f3f2306dad7a7e1bdcd65636f1177
- name: PROJECT/BROADCASTER
  newName: tsadom/dwkex
  newTag: broadcaster.35665ff4660f3f2306dad7a7e1bdcd65636f1177
- name: PROJECT/CRON
  newName: tsadom/dwkex
  newTag: cron.35665ff4660f3f2306dad7a7e1bdcd65636f1177
- name: PROJECT/FRONTEND
  newName: tsadom/dwkex
  newTag: frontend.35665ff4660f3f2306dad7a7e1bdcd65636f1177
