apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/db/statefulset.yaml
- manifests/db/service.yaml
- manifests/frontend/deployment.yaml
- manifests/frontend/service.yaml
- manifests/backend/rollout.yaml
- manifests/backend/service.yaml
- manifests/backend/horizontalpodautoscaler.yaml
- manifests/cron/job.yaml
- manifests/broadcaster/deployment.yaml
- manifests/ingress.yaml
- manifests/analysistemplate.yaml
- persistent/persistentvolumeclaim.yaml
- persistent/persistentvolume.yaml
images:
- name: PROJECT/BACKEND
  newName: tsa-dom/dwkex
  newTag: backend.a3c2c4e786204f9e85dab8acae37d6f517381898
- name: PROJECT/BROADCASTER
  newName: tsa-dom/dwkex
  newTag: broadcaster.a3c2c4e786204f9e85dab8acae37d6f517381898
- name: PROJECT/CRON
  newName: tsa-dom/dwkex
  newTag: cron.a3c2c4e786204f9e85dab8acae37d6f517381898
- name: PROJECT/FRONTEND
  newName: tsa-dom/dwkex
  newTag: frontend.a3c2c4e786204f9e85dab8acae37d6f517381898
