apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/secrets/secret.enc.yaml
- manifests/secrets/psql-sa-key.enc.yaml
- manifests/configmap.yaml
- manifests/db/statefulset.yaml
- manifests/db/service.yaml
- manifests/frontend/deployment.yaml
- manifests/frontend/service.yaml
- manifests/backend/rollout.yaml
- manifests/backend/service.yaml
- manifests/backend/horizontalpodautoscaler.yaml
- manifests/cron/job.yaml
- manifests/broadcaster/deployment.yaml
- manifests/ingress.yaml
- manifests/analysistemplate.yaml
- persistent/persistentvolumeclaim.yaml
- persistent/persistentvolume.yaml
images:
- name: PROJECT/BACKEND
  newName: tsadom/dwkex
  newTag: backend.f443d2e87b23d1643419395a39d6d68b773df85f
- name: PROJECT/BROADCASTER
  newName: tsadom/dwkex
  newTag: broadcaster.f443d2e87b23d1643419395a39d6d68b773df85f
- name: PROJECT/CRON
  newName: tsadom/dwkex
  newTag: cron.f443d2e87b23d1643419395a39d6d68b773df85f
- name: PROJECT/FRONTEND
  newName: tsadom/dwkex
  newTag: frontend.f443d2e87b23d1643419395a39d6d68b773df85f
