apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-broadcaster
  namespace: project
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-broadcaster
    spec:
      containers:
      - env:
        - name: NATS_URL
          value: nats://my-nats:4222
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              key: DISCORD_BOT_TOKEN
              name: secrets
        image: PROJECT/BROADCASTER
        name: todo-broadcaster