apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: postgres-svc
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
  - name: web
    protocol: TCP
    port: 5432
  selector:
    app: postgresapp