apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: todo-backend-dep
spec:
  serviceName: todo-backend-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/BACKEND
          volumeMounts:
          - name: shared-image
            mountPath: /usr/app/files
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: config-file
                  key: PG_HOST
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: config-file
                  key: PG_DATABASE
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: config-file
                  key: PG_PORT
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_PASSWORD

  volumeClaimTemplates:
    - metadata:
        name: shared-image
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi