apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: dwk-backend
spec:
  serviceName: todo-backend-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=dwk-gke-333411:europe-north1:postgres=tcp:5432"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "500Mi"
          volumeMounts:
            - name: psql-secret
              mountPath: /secrets/
              readOnly: true
        - name: todo-backend
          image: PROJECT/BACKEND
          resources:
            requests:
              cpu: "28m"
              memory: "100Mi"
            limits:
              cpu: "28m"
              memory: "100Mi"
          volumeMounts:
          - name: shared-image
            mountPath: /usr/app/files
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: config-file
                  key: PG_HOST
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: config-file
                  key: PG_DATABASE
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: config-file
                  key: PG_PORT
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_PASSWORD
      volumes:
      - name: psql-secret
        secret:
          secretName: psql-sa-key

  volumeClaimTemplates:
    - metadata:
        name: shared-image
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
