apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      volumes:
        - name: shared-image
          emptyDir: {}
      containers:
        - name: todo-project
          image: tsadom/dwkex:12.1
          volumeMounts:
          - name: shared-image
            mountPath: /usr/app/files