apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-frontend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-frontend
    spec:
      containers:
      - image: PROJECT/FRONTEND
        name: todo-frontend
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5