apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-frontend-svc
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80