apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log-pingpong
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: tsadom/dwkex:log-output.3
          resources:
            requests:
              cpu: "5m"
              memory: "100Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"
          envFrom:
            - configMapRef:
                name: config-file

          volumeMounts:
            - name: config
              mountPath: /config/conf
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 8080
          ports:
            - containerPort: 8080

      volumes:
        - name: config
          configMap:
            name: config-file
