apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log-pingpong
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: tsadom/dwkex:v3.2.log-output.13
          resources:
            requests:
              cpu: "5m"
              memory: "100Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"
          envFrom:
            - configMapRef:
                name: config-file

          volumeMounts:
            - name: config
              mountPath: /config/conf

      volumes:
        - name: config
          configMap:
            name: config-file
