apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: log-output-hpa
  namespace: log-pingpong
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-output-dep
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
