apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: log-output
  namespace: log-pingpong
spec:
  template:
    metadata:
      name: log-output-dwk
    spec:
      containers:
        - image: tsadom/dwkex:log-output.6
          envFrom:
            - configMapRef:
                name: config-file

          volumeMounts:
            - name: config
              mountPath: /config/conf

      volumes:
        - name: config
          configMap:
            name: config-file