apiVersion: v1
kind: Service
metadata:
  namespace: log-pingpong
  name: log-output-svc
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
