/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controllers

import (
	"context"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	stabledwkv1 "stable.dwk/api/v1"
)

// DummySiteReconciler reconciles a DummySite object
type DummySiteReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

//+kubebuilder:rbac:groups=stable.dwk.stable.dwk,resources=dummysites,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=stable.dwk.stable.dwk,resources=dummysites/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=stable.dwk.stable.dwk,resources=dummysites/finalizers,verbs=update

// Reconcile is part of the main kubernetes reconciliation loop which aims to
// move the current state of the cluster closer to the desired state.
// TODO(user): Modify the Reconcile function to compare the state specified by
// the DummySite object against the actual cluster state, and then
// perform operations to make the cluster state reflect the state specified by
// the user.
//
// For more details, check Reconcile and its Result here:
// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.10.0/pkg/reconcile

func constructDummyService(dummySite *stabledwkv1.DummySite, r *DummySiteReconciler) (*unstructured.Unstructured, error) {

	// Auto-generated by kyaml2go - https://github.com/PrasadG193/kyaml2go
	svc := &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "Service",
			"metadata": map[string]interface{}{
				"name":      "dummysite-controller-svc",
				"namespace": dummySite.Namespace,
			},
			"spec": map[string]interface{}{
				"ports": []interface{}{
					map[string]interface{}{
						"name":       "http",
						"port":       80,
						"protocol":   "TCP",
						"targetPort": 8080,
					},
				},
				"selector": map[string]interface{}{
					"app": "dummysite-controller",
				},
				"type": "ClusterIP",
			},
		},
	}

	if err := ctrl.SetControllerReference(dummySite, svc, r.Scheme); err != nil {
		return nil, err
	}

	return svc, nil
}

func constructDummyIngress(dummySite *stabledwkv1.DummySite, r *DummySiteReconciler) (*unstructured.Unstructured, error) {

	// Auto-generated by kyaml2go - https://github.com/PrasadG193/kyaml2go
	ing := &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "networking.k8s.io/v1",
			"kind":       "Ingress",
			"metadata": map[string]interface{}{
				"name":      "dummysite-ing",
				"namespace": dummySite.Namespace,
			},
			"spec": map[string]interface{}{
				"rules": []interface{}{
					map[string]interface{}{
						"http": map[string]interface{}{
							"paths": []interface{}{
								map[string]interface{}{
									"backend": map[string]interface{}{
										"service": map[string]interface{}{
											"name": "dummysite-controller-svc",
											"port": map[string]interface{}{
												"number": 80,
											},
										},
									},
									"path":     "/",
									"pathType": "Prefix",
								},
							},
						},
					},
				},
			},
		},
	}

	if err := ctrl.SetControllerReference(dummySite, ing, r.Scheme); err != nil {
		return nil, err
	}

	return ing, nil
}

func (r *DummySiteReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	_ = log.FromContext(ctx)
	ctrl.Log.Info("This is awesome")

	var dummySite stabledwkv1.DummySite
	if err := r.Get(ctx, req.NamespacedName, &dummySite); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	svc, err := constructDummyService(&dummySite, r)

	if err != nil {
		return ctrl.Result{}, err
	}

	if err := r.Create(ctx, svc); err != nil {
		return ctrl.Result{}, err
	}

	ing, err := constructDummyIngress(&dummySite, r)

	if err != nil {
		return ctrl.Result{}, err
	}

	if err := r.Create(ctx, ing); err != nil {
		return ctrl.Result{}, err
	}

	// TODO(user): your logic here

	return ctrl.Result{}, nil
}

// SetupWithManager sets up the controller with the Manager.
func (r *DummySiteReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&stabledwkv1.DummySite{}).
		Complete(r)
}

// https://kyaml2go.prasadg.dev/
