name: Release Project

on:
  push:
    branches:
      - main
    paths:
      - 'Project/**'
      - '.github/workflows/publish.yaml'

jobs:
  build:
    name: Build
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Frontend
      uses: docker/build-push-action@v2
      with:
        context: Project/frontend
        push: true
        tags: tsadom/dwkex:frontend.${{ github.sha }}

    - name: Build and Push Backend
      uses: docker/build-push-action@v2
      with:
        context: Project/backend
        push: true
        tags: tsadom/dwkex:backend.${{ github.sha }}

    - name: Build and Push Cron
      uses: docker/build-push-action@v2
      with:
        context: Project/cron
        push: true
        tags: tsadom/dwkex:cron.${{ github.sha }}

    - name: Build and Push Broadcaster
      uses: docker/build-push-action@v2
      with:
        context: Project/broadcaster
        push: true
        tags: tsadom/dwkex:broadcaster.${{ github.sha }}

    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: build

      steps:
      - uses: actions/checkout@v2

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update yamls
        working-directory: Project
        run: |
          kustomize edit set image PROJECT/FRONTEND=tsadom/dwkex:frontend.${{ github.sha }}
          kustomize edit set image PROJECT/BACKEND=tsadom/dwkex:backend.${{ github.sha }}
          kustomize edit set image PROJECT/CRON=tsadom/dwkex:cron.${{ github.sha }}
          kustomize edit set image PROJECT/BROADCASTER=tsadom/dwkex:broadcaster.${{ github.sha }}
      
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'Project/kustomization.yaml'
          message: New version release for gitops-project ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}